#!/bin/sh

cp -R stardict-test_dict-2.4.2 "${HOME}"/.stardict/dic
unset SDCV_PAGER
RES=`../src/sdcv -n -u test_dict test | grep "test passed"`

if [ -z "$RES" ]; then
	echo "we didn't find in stardict-test_dict-2.4.2 "test" keyword, something wrong" >&2
	exit 1
fi

rm -fr "${HOME}"/.stardict/dic/stardict-test_dict-2.4.2

exit 0
