name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 02 */4 * *'
env:
  RUST_BACKTRACE: 1
jobs:
  tests:
    name: Run tests

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true

      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.10'
          github-api-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check versions
        run: |
          set -e
          cmake --version
          gcc --version
          echo "end of versions checking"
        shell: bash
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libglib2.0-dev
          version: 1.0
      - name: Run tests
        run: |
          set -e
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake -DBUILD_TESTS=True ..
          make -k -j2 VERBOSE=1
          ctest --output-on-failure
        shell: bash
